version: "3"
services:

  db:
    image: postgres:9.4
    networks:
      - backend
      - frontend
    deploy:
      placement:
        constraints: [node.role == manager]

  vote:
    image: witsec/votingapp_vote:latest
    ports:
      - 5000:80
    networks:
      - frontend
    depends_on:
      - db
    deploy:
      replicas: 4

  result:
    image: witsec/votingapp_result:latest
    ports:
      - 6000:80
    networks:
      - backend
    depends_on:
      - db
    deploy:
      replicas: 1

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - 7000:8080
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  frontend:
  backend:
